/** Canonical non-technical internship domains for arts / commerce / humanities registration. */
export const NON_TECHNICAL_INTERNSHIP_DOMAINS: readonly string[] = [
  "Accounting & Tally with GST",
  "Accounting, Tally & GST",
  "Arabic Content Writing & Copywriting using AI Tools",
  "Archaeological Survey & Excavation Research Heritage Conservation & Monument Restoration",
  "Banking & Finance",
  "Bengali Content Writing & Copywriting using AI Tools",
  "Buddhist Studies & Heritage Research",
  "Business Analytics",
  "Business Development",
  "Career Counselling",
  "Clinical Counseling & Mental Health",
  "Content writing",
  "Corporate Legal Compliance & Governance",
  "Digital Archives & Heritage Documentation",
  "Digital Marketing",
  "Digital Marketing & Social Media Management",
  "Disaster Management & Risk Assessment",
  "E-Commerce",
  "Entrepreneurship",
  "ESG (Environmental, Social, Governance) Research",
  "Ethnographic Field Research",
  "Financial Analysis",
  "Financial Mathematics & Stock Market Basics",
  "Herbal & Ayurvedic Product Development",
  "Heritage Conservation & Monument Restoration",
  "Hindi Content Writing & Copywriting using AI Tools",
  "Hindi Journalism & News Media Production",
  "Historical Content Writing & SEO Blogging",
  "HR Operations & Employee Lifecycle Management",
  "Human Resource Management",
  "Human Rights & NGO Legal Advocacy",
  "Jain Studies & Heritage Research",
  "Journalism, Media & Public Relations",
  "Maithili Content Writing & Copywriting using AI Tools",
  "Marketing & Sales",
  "Mental Health & Philosophical Counseling",
  "Microfinance & Rural Banking",
  "Music Production & Audio Engineering (DAW)",
  "NGO & Social Work",
  "Operations Management",
  "Organic Farming & Sustainable Agriculture",
  "Pali Content Writing & Copywriting using AI Tools",
  "Persian Content Writing & Copywriting using AI Tools",
  "Personal Finance & Financial Planning",
  "Philosophy and human values in modern life",
  "Political Journalism & Digital News Media",
  "Prakit Content Writing & Copywriting using AI Tools",
  "Public Health & Social Welfare Research",
  "Research Methodology",
  "Sales Fundamentals & B2B/B2C Selling Skills",
  "Sanskrit Content Writing & Copywriting using AI Tools",
  "School Administration & Classroom Management",
  "Scriptwriting & Creative Storytelling",
  "Social Media Management",
  "Spoken English & Communication Skills",
  "Stock Market",
  "Teacher Training",
  "Teaching & Pedagogy",
  "Urdu Content Writing & Copywriting using AI Tools",
] as const;
