/** Canonical non-technical internship domains for arts / commerce / humanities registration. */
export const NON_TECHNICAL_INTERNSHIP_DOMAINS: readonly string[] = [
  "Business Management",
  "Business Administration",
  "Operations Management",
  "Project Management",
  "Product Management",
  "Strategic Management",
  "General Management",
  "Business Development",
  "Entrepreneurship",
  "Startup Management",
  "International Business",
  "Supply Chain Management",
  "Logistics Management",
  "Retail Management",
  "Event Management",
  "Hospitality Management",
  "Hotel Management",
  "Tourism Management",
  "Aviation Management",
  "Sales & Marketing",
  "Sales",
  "Marketing",
  "Digital Marketing",
  "Social Media Marketing",
  "Content Marketing",
  "Influencer Marketing",
  "Brand Management",
  "Product Marketing",
  "Performance Marketing",
  "Search Engine Optimization (SEO)",
  "Search Engine Marketing (SEM)",
  "Public Relations (PR)",
  "Advertising",
  "Market Research",
  "Customer Relationship Management (CRM)",
  "Telemarketing",
  "Business Development & Sales",
  "Retail Sales",
  "E-commerce Management",
  "Finance",
  "Accounting",
  "Auditing",
  "Taxation",
  "Banking",
  "Investment Banking",
  "Financial Planning",
  "Financial Analysis",
  "Insurance",
  "Wealth Management",
  "Risk Management",
  "Stock Market & Equity Research",
  "Corporate Finance",
  "Cost Accounting",
  "GST",
  "Microfinance",
  "FinTech Business/Operations",
  "Human Resources (HR)",
  "Recruitment",
  "Talent Acquisition",
  "Talent Management",
  "Employee Relations",
  "Learning & Development",
  "Training & Development",
  "Payroll Management",
  "Performance Management",
  "Organizational Development",
  "HR Operations",
  "English",
  "Hindi",
  "Literature",
  "History",
  "Political Science",
  "Sociology",
  "Psychology",
  "Philosophy",
  "Geography",
  "Economics",
  "Anthropology",
  "Social Work",
  "International Relations",
  "Public Administration",
  "Development Studies",
  "Gender Studies",
  "Cultural Studies",
  "Rural Development",
  "Human Rights",
  "Journalism",
  "Mass Communication",
  "Media Studies",
  "Public Relations",
  "Corporate Communication",
  "Content Writing",
  "Copywriting",
  "Creative Writing",
  "Editing & Publishing",
  "Broadcasting",
  "Radio",
  "Television",
  "Photography",
  "Film & Media Production",
  "Digital Media",
  "Graphic Design",
  "Fashion Design",
  "Interior Design",
  "Product Design",
  "Textile Design",
  "Fashion Merchandising",
  "Animation",
  "Illustration",
  "Fine Arts",
  "Visual Arts",
  "Performing Arts",
  "Music",
  "Dance",
  "Theatre",
  "Video Production",
  "Creative Direction",
  "Teaching",
  "Education",
  "Early Childhood Education",
  "Primary Education",
  "Secondary Education",
  "Special Education",
  "Educational Psychology",
  "Curriculum Development",
  "Academic Counseling",
  "Career Counseling",
  "Educational Administration",
  "Training & Facilitation",
  "E-learning Content Development",
  "Law",
  "Legal Research",
  "Corporate Law",
  "Criminal Law",
  "Civil Law",
  "Constitutional Law",
  "Intellectual Property Law",
  "Cyber Law",
  "Labour Law",
  "Tax Law",
  "Human Rights Law",
  "Legal Compliance",
  "Legal Operations",
  "Paralegal Services",
  "Healthcare Management",
  "Hospital Administration",
  "Healthcare Operations",
  "Public Health",
  "Health Administration",
  "Medical Administration",
  "Healthcare Marketing",
  "Healthcare HR",
  "Medical Research",
  "Community Health",
  "Nutrition & Wellness",
  "Health Education",
  "Pharmaceutical Management",
  "Clinical Research",
  "Healthcare Counseling",
  "NGO Management",
  "Community Development",
  "CSR (Corporate Social Responsibility)",
  "Fundraising",
  "Volunteer Management",
  "Humanitarian Services",
  "Child Welfare",
  "Women Empowerment",
  "Youth Development",
  "Poverty Alleviation",
  "Community Outreach",
  "Nonprofit Management",
  "Social Entrepreneurship",
  "Government Affairs",
  "Public Policy",
  "Policy Research",
  "Governance",
  "Rural Administration",
  "Urban Development",
  "Development Administration",
  "Political Research",
  "Election & Political Campaign Management",
  "Government Scheme Research",
  "Environmental Management",
  "Environmental Policy",
  "Sustainability",
  "Sustainable Development",
  "Climate Change",
  "Renewable Energy Management",
  "Waste Management",
  "Environmental Awareness",
  "ESG (Environmental, Social & Governance)",
  "Conservation Management",
  "Wildlife Conservation",
  "Forestry Management",
  "Social Research",
  "Economic Research",
  "Consumer Research",
  "Academic Research",
  "Qualitative Research",
  "Survey Research",
  "Research & Documentation",
  "E-commerce Operations",
  "Customer Service",
  "Customer Support",
  "Customer Success",
  "Order Management",
  "Marketplace Management",
  "Vendor Management",
  "Procurement",
  "Inventory Management",
  "Merchandising",
  "Business Operations",
  "Administration",
  "Office Administration",
  "Executive Assistance",
  "Documentation",
  "Data Entry",
  "Translation",
  "Language Services",
  "Library Management",
  "Records Management",
  "Procurement Management",
  "Quality Management",
  "Compliance",
  "Corporate Affairs",
  "Public Affairs",
  "Personal Assistant / Executive Assistant",
  "Secretarial Services",
] as const;
