/** Canonical technical internship domains for engineering / BEU registration. */
export const TECHNICAL_INTERNSHIP_DOMAINS: readonly string[] = [
  "AI Ethics & Responsible Technology Policy Research",
  "Ardunio & Embedded Systems",
  "Artificial Intelligence & Machine Learning",
  "AutoCAD Civil",
  "AutoCAD Mechanical",
  "Automobile Engineering",
  "Automobile Project Management",
  "Biomedical Research",
  "Biotechnology & Microbiology",
  "Building Construction & Site Supervision",
  "C/C++ Programming",
  "Climate Change & Carbon Analytics Research",
  "Cloud Computing",
  "Construction Project Management",
  "Cyber Security",
  "Cybersecurity",
  "Data Science & Data Analytics",
  "Digital Teaching & Content Development",
  "Educational Technology",
  "Electric Vehicle (EV) Technology",
  "Electrical Design",
  "Embedded Systems",
  "Environmental Science",
  "Food Technology & FMCG Product Development",
  "Full Stack Development",
  "Genetics & Biotechnology Basics for Zoologists",
  "GIS (Geographic Information Systems) Analysis",
  "GIS & Remote Sensing",
  "Graphic Designing",
  "Industrial Automation - PLC & SCADA",
  "Internet of Things (IoT)",
  "Java Programming",
  "Manufacturing & Production Management",
  "Mine Environment and Pollution Control",
  "Mine Safety and Ventilation",
  "Mine Surveying",
  "Mineral Processing",
  "Mobile App Development",
  "PCB Design",
  "Pharmaceutical Industry Basics & Drug Chemistry",
  "PLC+Scada",
  "Python Programming",
  "Quantity Surveying & Estimation",
  "Renewable Energy System",
  "Robotics",
  "Robotics & Arduino",
  "Software Testing",
  "Solar & Renewable Energy",
  "Solar Energy & Photovoltaic Systems",
  "SolidWorks & CAD/CAM",
  "Structural Design",
  "Surface Mining Operation",
  "UI/UX Design",
  "Underground Drilling and Blasting",
  "Web Development",
] as const;
