/** Canonical technical internship domains for engineering / BEU registration. */
export const TECHNICAL_INTERNSHIP_DOMAINS: readonly string[] = [
  "Software Development",
  "Web Development",
  "Frontend Development",
  "Backend Development",
  "Full Stack Development",
  "Mobile App Development",
  "Android Development",
  "iOS Development",
  "Cross-Platform App Development",
  "React.js Development",
  "Angular Development",
  "Vue.js Development",
  "Node.js Development",
  "Java Development",
  "Python Development",
  "C/C++ Development",
  "C# / .NET Development",
  "PHP Development",
  "Laravel Development",
  "Java Spring Boot Development",
  "Flutter Development",
  "React Native Development",
  "DevOps",
  "Cloud Computing",
  "AWS Cloud",
  "Microsoft Azure",
  "Google Cloud Platform (GCP)",
  "Cloud Architecture",
  "Cybersecurity",
  "Ethical Hacking",
  "Network Security",
  "Information Security",
  "Application Security",
  "Penetration Testing",
  "Digital Forensics",
  "Data Science",
  "Data Analytics",
  "Data Engineering",
  "Big Data",
  "Business Intelligence",
  "Machine Learning",
  "Deep Learning",
  "Artificial Intelligence",
  "Generative AI",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Robotics",
  "Internet of Things (IoT)",
  "Embedded Systems",
  "VLSI Design",
  "Semiconductor Technology",
  "FPGA Development",
  "Embedded Software",
  "Firmware Development",
  "Blockchain",
  "Web3 Development",
  "Smart Contract Development",
  "Cryptocurrency Technology",
  "Database Management",
  "SQL Development",
  "Database Administration",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Oracle Database",
  "UI/UX Design",
  "Product Design",
  "Software Testing",
  "Quality Assurance (QA)",
  "Automation Testing",
  "Manual Testing",
  "Performance Testing",
  "API Testing",
  "Game Development",
  "AR/VR Development",
  "3D Development",
  "Computer Graphics",
  "GIS & Geospatial Technology",
  "Network Engineering",
  "System Administration",
  "IT Infrastructure",
  "Technical Support / IT Support",
  "Site Reliability Engineering (SRE)",
  "Platform Engineering",
  "Kubernetes & Containerization",
  "Docker",
  "Linux Administration",
  "Enterprise Software Development",
  "ERP Development",
  "CRM Development",
  "API Development",
  "Microservices Architecture",
  "Software Architecture",
  "Solutions Architecture",
  "Automation & RPA",
  "Robotic Process Automation",
  "Data Visualization",
  "Technical Research & Development",
  "Computer Science Research",
  "Information Technology",
] as const;
