#!/usr/bin/env bash
# Apna Intern — automated AWS staging setup (RDS + S3 + Lambda).
#
# Prerequisites:
#   1. AWS account + IAM user with AdministratorAccess (or CloudFormation + RDS + Lambda + S3 + SES)
#   2. Copy .env.setup.example → .env and fill in secrets
#   3. bash scripts/install-aws-tools.sh
#
# Usage:
#   bash scripts/setup-apnaintern-aws.sh check     # verify AWS credentials
#   bash scripts/setup-apnaintern-aws.sh s3        # create S3 buckets
#   bash scripts/setup-apnaintern-aws.sh rds       # create RDS PostgreSQL
#   bash scripts/setup-apnaintern-aws.sh export    # export Supabase → SQL backup
#   bash scripts/setup-apnaintern-aws.sh import    # import backup into RDS
#   bash scripts/setup-apnaintern-aws.sh lambda    # deploy API to Lambda
#   bash scripts/setup-apnaintern-aws.sh all       # s3 → rds → export → import → lambda
#
# SES domain verification must be done manually in AWS Console (DNS records).

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

export PATH="$HOME/.local/bin:$ROOT/aws/.venv/bin:$PATH"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}▶${NC} $*"; }
warn()  { echo -e "${YELLOW}⚠${NC} $*"; }
fail()  { echo -e "${RED}❌${NC} $*"; exit 1; }

load_env() {
  if [[ ! -f "$ROOT/.env" ]]; then
    fail "Missing .env — copy .env.setup.example to .env and fill in your secrets."
  fi
  set -a
  # shellcheck disable=SC1091
  source "$ROOT/.env"
  set +a
}

load_aws_creds() {
  load_env
  if ! command -v aws >/dev/null 2>&1; then
    fail "AWS CLI not found. Run: bash scripts/install-aws-tools.sh"
  fi
  if ! aws sts get-caller-identity --region "${AWS_DEFAULT_REGION:-ap-south-1}" >/dev/null 2>&1; then
    fail "AWS credentials invalid. Check AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY in .env"
  fi
}

cmd_check() {
  load_aws_creds
  info "AWS identity:"
  aws sts get-caller-identity --output table

  local missing=()
  [[ -z "${VITE_SUPABASE_URL:-}" ]] && missing+=("VITE_SUPABASE_URL")
  [[ -z "${VITE_SUPABASE_PUBLISHABLE_KEY:-}" ]] && missing+=("VITE_SUPABASE_PUBLISHABLE_KEY")
  [[ -z "${RAZORPAY_KEY_ID:-}" && -z "${VITE_RAZORPAY_KEY_ID:-}" ]] && missing+=("RAZORPAY_KEY_ID")
  [[ -z "${RAZORPAY_KEY_SECRET:-}" ]] && missing+=("RAZORPAY_KEY_SECRET")
  [[ -z "${SMTP_USER:-}" ]] && missing+=("SMTP_USER")
  [[ -z "${SMTP_PASS:-}" ]] && missing+=("SMTP_PASS")

  if ((${#missing[@]})); then
    warn "Missing in .env (needed for Lambda deploy): ${missing[*]}"
  else
    info "All Lambda env keys present in .env"
  fi

  if [[ -z "${SUPABASE_DB_URL:-}" ]]; then
    warn "SUPABASE_DB_URL not set — export step will be skipped"
  fi

  if [[ -z "${DATABASE_URL:-}" ]]; then
    warn "DATABASE_URL not set — run 'rds' step first or paste RDS connection string into .env"
  else
    info "DATABASE_URL is set"
  fi

  echo ""
  info "Ready for: bash scripts/setup-apnaintern-aws.sh all"
}

write_awsrds_local() {
  if [[ -z "${DATABASE_URL:-}" ]]; then
    warn "Skipping .env.awsrds.local — DATABASE_URL not set"
    return
  fi

  cat > "$ROOT/.env.awsrds.local" <<EOF
# Auto-generated by scripts/setup-apnaintern-aws.sh — do not commit
DATABASE_URL=${DATABASE_URL}

VITE_SUPABASE_URL=http://localhost:8080
VITE_SUPABASE_PUBLISHABLE_KEY=local-anon-key
VITE_SUPABASE_PROJECT_ID=apnaintern-local
LOCAL_SUPABASE=true
LOCAL_JWT_SECRET=${LOCAL_JWT_SECRET:-change-me-local-secret-min-32-chars}
RDS_RPC_OPEN=true

VITE_SITE_API_ORIGIN=http://localhost:8080
VITE_PUBLIC_APP_URL=http://localhost:8080
VITE_RAZORPAY_KEY_ID=${VITE_RAZORPAY_KEY_ID:-${RAZORPAY_KEY_ID:-}}

S3_BUCKET_CONSENT_FORMS=${S3_BUCKET_CONSENT_FORMS:-ezyintern-staging-consent-forms}
S3_BUCKET_LOGOS=${S3_BUCKET_LOGOS:-ezyintern-staging-logos}
S3_BUCKET_LEARNING_MATERIALS=${S3_BUCKET_LEARNING_MATERIALS:-ezyintern-staging-learning-materials}
S3_BUCKET_ASSIGNMENT_UPLOADS=${S3_BUCKET_ASSIGNMENT_UPLOADS:-ezyintern-staging-learning-materials}
AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-ap-south-1}
EOF
  info "Wrote .env.awsrds.local"
}

write_aws_local() {
  local api_url="${API_BASE_URL:-}"
  if [[ -z "$api_url" ]]; then
    api_url="$(aws cloudformation describe-stacks \
      --stack-name ezyintern-api-staging \
      --region "${AWS_DEFAULT_REGION:-ap-south-1}" \
      --query "Stacks[0].Outputs[?OutputKey=='ApiBaseUrl'].OutputValue" \
      --output text 2>/dev/null || true)"
  fi

  if [[ -z "$api_url" || "$api_url" == "None" ]]; then
    warn "ApiBaseUrl not found — set VITE_SITE_API_ORIGIN manually in .env.aws.local after lambda deploy"
    return
  fi

  cat > "$ROOT/.env.aws.local" <<EOF
# Auto-generated by scripts/setup-apnaintern-aws.sh — do not commit
VITE_SUPABASE_URL=${VITE_SUPABASE_URL:-}
VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY:-}
VITE_SUPABASE_PROJECT_ID=${VITE_SUPABASE_PROJECT_ID:-}

VITE_SITE_API_ORIGIN=${api_url}
VITE_PUBLIC_APP_URL=${api_url}
VITE_RAZORPAY_KEY_ID=${VITE_RAZORPAY_KEY_ID:-${RAZORPAY_KEY_ID:-}}
EOF
  info "Wrote .env.aws.local (API: $api_url)"
}

cmd_s3() {
  load_aws_creds
  info "Provisioning S3 buckets..."
  npm run aws:s3:provision
}

cmd_rds() {
  load_aws_creds
  if [[ -z "${RDS_MASTER_PASSWORD:-}" ]]; then
    fail "Set RDS_MASTER_PASSWORD in .env (min 12 characters)"
  fi
  export RDS_MASTER_PASSWORD
  export ALLOWED_CIDR="${ALLOWED_CIDR:-$(curl -fsSL https://checkip.amazonaws.com)/32}"
  info "Provisioning RDS (allowed CIDR: $ALLOWED_CIDR)..."
  npm run aws:rds:provision

  warn "Copy the DATABASE_URL from the output above into .env, then re-run: setup-apnaintern-aws.sh import"
}

cmd_export() {
  load_env
  if [[ -z "${SUPABASE_DB_URL:-}" ]]; then
    fail "Set SUPABASE_DB_URL in .env (Supabase → Database → URI)"
  fi
  export SUPABASE_DB_URL
  info "Exporting Supabase database (read-only)..."
  npm run aws:rds:export:full
}

cmd_import() {
  load_env
  write_awsrds_local
  local backup
  backup="$(ls -t "$ROOT/aws/backups"/full_*.sql 2>/dev/null | head -1 || true)"
  if [[ -z "$backup" ]]; then
    fail "No backup found in aws/backups/full_*.sql — run export first"
  fi
  info "Importing $backup into RDS..."
  npm run aws:rds:import -- --restore "$backup"
  npm run aws:rds:verify
}

cmd_lambda() {
  load_aws_creds
  write_awsrds_local
  if [[ ! -f "$ROOT/.env.awsrds.local" ]] || ! grep -q '^DATABASE_URL=postgresql' "$ROOT/.env.awsrds.local" 2>/dev/null; then
    fail "DATABASE_URL missing. Complete RDS + import first."
  fi
  if ! command -v sam >/dev/null 2>&1; then
    bash "$ROOT/scripts/install-aws-tools.sh"
  fi
  info "Deploying Lambda API..."
  npm run aws:lambda:deploy
  write_aws_local
  info "Health check:"
  local url
  url="$(grep '^VITE_SITE_API_ORIGIN=' "$ROOT/.env.aws.local" 2>/dev/null | cut -d= -f2- || true)"
  if [[ -n "$url" ]]; then
    curl -fsSL "${url}/api/health" && echo "" || warn "Health check failed — check CloudWatch logs"
  fi
}

cmd_ses_guide() {
  cat <<'EOF'

── Amazon SES (manual — requires DNS access) ─────────────────────
1. AWS Console → SES → region ap-south-1
2. Verified identities → Create → Domain → apnaintern.in
3. Add DKIM/CNAME records at your domain registrar
4. Request production access (leave sandbox)
5. SMTP settings → Create SMTP credentials → add to .env:
     SMTP_USER, SMTP_PASS, MAIL_FROM=Apna Intern <admin@apnaintern.in>

EOF
}

cmd_all() {
  cmd_check
  cmd_s3
  if [[ -z "${DATABASE_URL:-}" ]]; then
    cmd_rds
    warn "Add DATABASE_URL to .env from RDS output, then run:"
    warn "  bash scripts/setup-apnaintern-aws.sh export"
    warn "  bash scripts/setup-apnaintern-aws.sh import"
    warn "  bash scripts/setup-apnaintern-aws.sh lambda"
    cmd_ses_guide
    exit 0
  fi
  if [[ -n "${SUPABASE_DB_URL:-}" ]]; then
    cmd_export
  fi
  cmd_import
  cmd_lambda
  cmd_ses_guide
  echo ""
  info "Setup complete. Test locally: npm run dev:aws"
  info "Add Lambda URL to Vercel Preview env: VITE_SITE_API_ORIGIN"
}

usage() {
  cat <<EOF
Apna Intern AWS setup

  bash scripts/setup-apnaintern-aws.sh <command>

Commands:
  check    Verify AWS credentials and .env
  s3       Create S3 staging buckets
  rds      Create RDS PostgreSQL instance
  export   Export Supabase DB to aws/backups/
  import   Import latest backup into RDS
  lambda   Deploy API to AWS Lambda
  ses      Print SES DNS setup instructions
  all      Run full pipeline (may pause after RDS for DATABASE_URL)

First time:
  cp .env.setup.example .env    # fill in secrets
  bash scripts/install-aws-tools.sh
  bash scripts/setup-apnaintern-aws.sh check

EOF
}

chmod +x "$ROOT/scripts/install-aws-tools.sh" 2>/dev/null || true

case "${1:-}" in
  check)  cmd_check ;;
  s3)     cmd_s3 ;;
  rds)    cmd_rds ;;
  export) cmd_export ;;
  import) cmd_import ;;
  lambda) cmd_lambda ;;
  ses)    cmd_ses_guide ;;
  all)    cmd_all ;;
  *)      usage ;;
esac
