-- Mirror of aws/scripts/74-rds-replace-non-technical-internship-domains.sql
-- Replace non-technical internship domains with the final 59-domain catalog.

WITH new_domain_names(name) AS (
  VALUES
    ('Accounting & Tally with GST'),
    ('Accounting, Tally & GST'),
    ('Arabic Content Writing & Copywriting using AI Tools'),
    ('Archaeological Survey & Excavation Research Heritage Conservation & Monument Restoration'),
    ('Banking & Finance'),
    ('Bengali Content Writing & Copywriting using AI Tools'),
    ('Buddhist Studies & Heritage Research'),
    ('Business Analytics'),
    ('Business Development'),
    ('Career Counselling'),
    ('Clinical Counseling & Mental Health'),
    ('Content writing'),
    ('Corporate Legal Compliance & Governance'),
    ('Digital Archives & Heritage Documentation'),
    ('Digital Marketing'),
    ('Digital Marketing & Social Media Management'),
    ('Disaster Management & Risk Assessment'),
    ('E-Commerce'),
    ('Entrepreneurship'),
    ('ESG (Environmental, Social, Governance) Research'),
    ('Ethnographic Field Research'),
    ('Financial Analysis'),
    ('Financial Mathematics & Stock Market Basics'),
    ('Herbal & Ayurvedic Product Development'),
    ('Heritage Conservation & Monument Restoration'),
    ('Hindi Content Writing & Copywriting using AI Tools'),
    ('Hindi Journalism & News Media Production'),
    ('Historical Content Writing & SEO Blogging'),
    ('HR Operations & Employee Lifecycle Management'),
    ('Human Resource Management'),
    ('Human Rights & NGO Legal Advocacy'),
    ('Jain Studies & Heritage Research'),
    ('Journalism, Media & Public Relations'),
    ('Maithili Content Writing & Copywriting using AI Tools'),
    ('Marketing & Sales'),
    ('Mental Health & Philosophical Counseling'),
    ('Microfinance & Rural Banking'),
    ('Music Production & Audio Engineering (DAW)'),
    ('NGO & Social Work'),
    ('Operations Management'),
    ('Organic Farming & Sustainable Agriculture'),
    ('Pali Content Writing & Copywriting using AI Tools'),
    ('Persian Content Writing & Copywriting using AI Tools'),
    ('Personal Finance & Financial Planning'),
    ('Philosophy and human values in modern life'),
    ('Political Journalism & Digital News Media'),
    ('Prakit Content Writing & Copywriting using AI Tools'),
    ('Public Health & Social Welfare Research'),
    ('Research Methodology'),
    ('Sales Fundamentals & B2B/B2C Selling Skills'),
    ('Sanskrit Content Writing & Copywriting using AI Tools'),
    ('School Administration & Classroom Management'),
    ('Scriptwriting & Creative Storytelling'),
    ('Social Media Management'),
    ('Spoken English & Communication Skills'),
    ('Stock Market'),
    ('Teacher Training'),
    ('Teaching & Pedagogy'),
    ('Urdu Content Writing & Copywriting using AI Tools')
),
legacy_domain_names(name) AS (
  VALUES
    ('Business Management'),
    ('Business Administration'),
    ('Project Management'),
    ('Product Management'),
    ('Strategic Management'),
    ('General Management'),
    ('Startup Management'),
    ('International Business'),
    ('Supply Chain Management'),
    ('Logistics Management'),
    ('Retail Management'),
    ('Event Management'),
    ('Hospitality Management'),
    ('Hotel Management'),
    ('Tourism Management'),
    ('Aviation Management'),
    ('Sales & Marketing'),
    ('Sales'),
    ('Marketing'),
    ('Social Media Marketing'),
    ('Content Marketing'),
    ('Influencer Marketing'),
    ('Brand Management'),
    ('Product Marketing'),
    ('Performance Marketing'),
    ('Search Engine Optimization (SEO)'),
    ('Search Engine Marketing (SEM)'),
    ('Public Relations (PR)'),
    ('Advertising'),
    ('Market Research'),
    ('Customer Relationship Management (CRM)'),
    ('Telemarketing'),
    ('Business Development & Sales'),
    ('Retail Sales'),
    ('E-commerce Management'),
    ('Finance'),
    ('Accounting'),
    ('Auditing'),
    ('Taxation'),
    ('Banking'),
    ('Investment Banking'),
    ('Financial Planning'),
    ('Insurance'),
    ('Wealth Management'),
    ('Risk Management'),
    ('Stock Market & Equity Research'),
    ('Corporate Finance'),
    ('Cost Accounting'),
    ('GST'),
    ('Microfinance'),
    ('FinTech Business/Operations'),
    ('Human Resources (HR)'),
    ('Recruitment'),
    ('Talent Acquisition'),
    ('Talent Management'),
    ('Employee Relations'),
    ('Learning & Development'),
    ('Training & Development'),
    ('Payroll Management'),
    ('Performance Management'),
    ('Organizational Development'),
    ('HR Operations'),
    ('English'),
    ('Hindi'),
    ('Literature'),
    ('History'),
    ('Political Science'),
    ('Sociology'),
    ('Psychology'),
    ('Philosophy'),
    ('Geography'),
    ('Economics'),
    ('Anthropology'),
    ('Social Work'),
    ('International Relations'),
    ('Public Administration'),
    ('Development Studies'),
    ('Gender Studies'),
    ('Cultural Studies'),
    ('Rural Development'),
    ('Human Rights'),
    ('Journalism'),
    ('Mass Communication'),
    ('Media Studies'),
    ('Public Relations'),
    ('Corporate Communication'),
    ('Content Writing'),
    ('Copywriting'),
    ('Creative Writing'),
    ('Editing & Publishing'),
    ('Broadcasting'),
    ('Radio'),
    ('Television'),
    ('Photography'),
    ('Film & Media Production'),
    ('Digital Media'),
    ('Graphic Design'),
    ('Fashion Design'),
    ('Interior Design'),
    ('Product Design'),
    ('Textile Design'),
    ('Fashion Merchandising'),
    ('Animation'),
    ('Illustration'),
    ('Fine Arts'),
    ('Visual Arts'),
    ('Performing Arts'),
    ('Music'),
    ('Dance'),
    ('Theatre'),
    ('Video Production'),
    ('Creative Direction'),
    ('Teaching'),
    ('Education'),
    ('Early Childhood Education'),
    ('Primary Education'),
    ('Secondary Education'),
    ('Special Education'),
    ('Educational Psychology'),
    ('Curriculum Development'),
    ('Academic Counseling'),
    ('Career Counseling'),
    ('Educational Administration'),
    ('Training & Facilitation'),
    ('E-learning Content Development'),
    ('Law'),
    ('Legal Research'),
    ('Corporate Law'),
    ('Criminal Law'),
    ('Civil Law'),
    ('Constitutional Law'),
    ('Intellectual Property Law'),
    ('Cyber Law'),
    ('Labour Law'),
    ('Tax Law'),
    ('Human Rights Law'),
    ('Legal Compliance'),
    ('Legal Operations'),
    ('Paralegal Services'),
    ('Healthcare Management'),
    ('Hospital Administration'),
    ('Healthcare Operations'),
    ('Public Health'),
    ('Health Administration'),
    ('Medical Administration'),
    ('Healthcare Marketing'),
    ('Healthcare HR'),
    ('Medical Research'),
    ('Community Health'),
    ('Nutrition & Wellness'),
    ('Health Education'),
    ('Pharmaceutical Management'),
    ('Clinical Research'),
    ('Healthcare Counseling'),
    ('NGO Management'),
    ('Community Development'),
    ('CSR (Corporate Social Responsibility)'),
    ('Fundraising'),
    ('Volunteer Management'),
    ('Humanitarian Services'),
    ('Child Welfare'),
    ('Women Empowerment'),
    ('Youth Development'),
    ('Poverty Alleviation'),
    ('Community Outreach'),
    ('Nonprofit Management'),
    ('Social Entrepreneurship'),
    ('Government Affairs'),
    ('Public Policy'),
    ('Policy Research'),
    ('Governance'),
    ('Rural Administration'),
    ('Urban Development'),
    ('Development Administration'),
    ('Political Research'),
    ('Election & Political Campaign Management'),
    ('Government Scheme Research'),
    ('Environmental Management'),
    ('Environmental Policy'),
    ('Sustainability'),
    ('Sustainable Development'),
    ('Climate Change'),
    ('Renewable Energy Management'),
    ('Waste Management'),
    ('Environmental Awareness'),
    ('ESG (Environmental, Social & Governance)'),
    ('Conservation Management'),
    ('Wildlife Conservation'),
    ('Forestry Management'),
    ('Social Research'),
    ('Economic Research'),
    ('Consumer Research'),
    ('Academic Research'),
    ('Qualitative Research'),
    ('Survey Research'),
    ('Research & Documentation'),
    ('E-commerce Operations'),
    ('Customer Service'),
    ('Customer Support'),
    ('Customer Success'),
    ('Order Management'),
    ('Marketplace Management'),
    ('Vendor Management'),
    ('Procurement'),
    ('Inventory Management'),
    ('Merchandising'),
    ('Business Operations'),
    ('Administration'),
    ('Office Administration'),
    ('Executive Assistance'),
    ('Documentation'),
    ('Data Entry'),
    ('Translation'),
    ('Language Services'),
    ('Library Management'),
    ('Records Management'),
    ('Procurement Management'),
    ('Quality Management'),
    ('Compliance'),
    ('Corporate Affairs'),
    ('Public Affairs'),
    ('Personal Assistant / Executive Assistant'),
    ('Secretarial Services')
)
DELETE FROM public.internship_domains d
USING legacy_domain_names l
WHERE d.name = l.name
  AND NOT EXISTS (SELECT 1 FROM new_domain_names n WHERE n.name = d.name);

INSERT INTO public.internship_domains (name)
SELECT n.name
FROM new_domain_names n
WHERE NOT EXISTS (
  SELECT 1 FROM public.internship_domains d WHERE d.name = n.name
);

UPDATE public.non_engineering_university_configs c
SET
  domains = (
    SELECT COALESCE(jsonb_agg(n.name ORDER BY n.name), '[]'::jsonb)
    FROM new_domain_names n
  ),
  updated_at = now()
WHERE c.is_active IS DISTINCT FROM false;
