-- Mirror of aws/scripts/73-rds-replace-technical-internship-domains.sql

WITH new_domain_names(name) AS (
  VALUES
    ('AI Ethics & Responsible Technology Policy Research'),
    ('Ardunio & Embedded Systems'),
    ('Artificial Intelligence & Machine Learning'),
    ('AutoCAD Civil'),
    ('AutoCAD Mechanical'),
    ('Automobile Engineering'),
    ('Automobile Project Management'),
    ('Biomedical Research'),
    ('Biotechnology & Microbiology'),
    ('Building Construction & Site Supervision'),
    ('C/C++ Programming'),
    ('Climate Change & Carbon Analytics Research'),
    ('Cloud Computing'),
    ('Construction Project Management'),
    ('Cyber Security'),
    ('Cybersecurity'),
    ('Data Science & Data Analytics'),
    ('Digital Teaching & Content Development'),
    ('Educational Technology'),
    ('Electric Vehicle (EV) Technology'),
    ('Electrical Design'),
    ('Embedded Systems'),
    ('Environmental Science'),
    ('Food Technology & FMCG Product Development'),
    ('Full Stack Development'),
    ('Genetics & Biotechnology Basics for Zoologists'),
    ('GIS (Geographic Information Systems) Analysis'),
    ('GIS & Remote Sensing'),
    ('Graphic Designing'),
    ('Industrial Automation - PLC & SCADA'),
    ('Internet of Things (IoT)'),
    ('Java Programming'),
    ('Manufacturing & Production Management'),
    ('Mine Environment and Pollution Control'),
    ('Mine Safety and Ventilation'),
    ('Mine Surveying'),
    ('Mineral Processing'),
    ('Mobile App Development'),
    ('PCB Design'),
    ('Pharmaceutical Industry Basics & Drug Chemistry'),
    ('PLC+Scada'),
    ('Python Programming'),
    ('Quantity Surveying & Estimation'),
    ('Renewable Energy System'),
    ('Robotics'),
    ('Robotics & Arduino'),
    ('Software Testing'),
    ('Solar & Renewable Energy'),
    ('Solar Energy & Photovoltaic Systems'),
    ('SolidWorks & CAD/CAM'),
    ('Structural Design'),
    ('Surface Mining Operation'),
    ('UI/UX Design'),
    ('Underground Drilling and Blasting'),
    ('Web Development')
),
legacy_domain_names(name) AS (
  VALUES
    ('Software Development'),
    ('Frontend Development'),
    ('Backend Development'),
    ('Android Development'),
    ('iOS Development'),
    ('Cross-Platform App Development'),
    ('React.js Development'),
    ('Angular Development'),
    ('Vue.js Development'),
    ('Node.js Development'),
    ('Java Development'),
    ('Python Development'),
    ('C# / .NET Development'),
    ('PHP Development'),
    ('Laravel Development'),
    ('Java Spring Boot Development'),
    ('Flutter Development'),
    ('React Native Development'),
    ('DevOps'),
    ('AWS Cloud'),
    ('Microsoft Azure'),
    ('Google Cloud Platform (GCP)'),
    ('Cloud Architecture'),
    ('Ethical Hacking'),
    ('Network Security'),
    ('Information Security'),
    ('Application Security'),
    ('Penetration Testing'),
    ('Digital Forensics'),
    ('Data Science'),
    ('Data Analytics'),
    ('Data Engineering'),
    ('Big Data'),
    ('Business Intelligence'),
    ('Machine Learning'),
    ('Deep Learning'),
    ('Artificial Intelligence'),
    ('Generative AI'),
    ('Natural Language Processing (NLP)'),
    ('Computer Vision'),
    ('VLSI Design'),
    ('Semiconductor Technology'),
    ('FPGA Development'),
    ('Embedded Software'),
    ('Firmware Development'),
    ('Blockchain'),
    ('Web3 Development'),
    ('Smart Contract Development'),
    ('Cryptocurrency Technology'),
    ('Database Management'),
    ('SQL Development'),
    ('Database Administration'),
    ('PostgreSQL'),
    ('MySQL'),
    ('MongoDB'),
    ('Oracle Database'),
    ('Product Design'),
    ('Quality Assurance (QA)'),
    ('Automation Testing'),
    ('Manual Testing'),
    ('Performance Testing'),
    ('API Testing'),
    ('Game Development'),
    ('AR/VR Development'),
    ('3D Development'),
    ('Computer Graphics'),
    ('GIS & Geospatial Technology'),
    ('Network Engineering'),
    ('System Administration'),
    ('IT Infrastructure'),
    ('Technical Support / IT Support'),
    ('Site Reliability Engineering (SRE)'),
    ('Platform Engineering'),
    ('Kubernetes & Containerization'),
    ('Docker'),
    ('Linux Administration'),
    ('Enterprise Software Development'),
    ('ERP Development'),
    ('CRM Development'),
    ('API Development'),
    ('Microservices Architecture'),
    ('Software Architecture'),
    ('Solutions Architecture'),
    ('Automation & RPA'),
    ('Robotic Process Automation'),
    ('Data Visualization'),
    ('Technical Research & Development'),
    ('Computer Science Research'),
    ('Information Technology')
)
DELETE FROM public.internship_domains d
USING legacy_domain_names l
WHERE d.name = l.name
  AND NOT EXISTS (SELECT 1 FROM new_domain_names n WHERE n.name = d.name);

INSERT INTO public.internship_domains (name)
SELECT n.name
FROM new_domain_names n
WHERE NOT EXISTS (
  SELECT 1 FROM public.internship_domains d WHERE d.name = n.name
);

UPDATE public.engineering_university_configs c
SET
  domains = (
    SELECT COALESCE(jsonb_agg(n.name ORDER BY n.name), '[]'::jsonb)
    FROM new_domain_names n
  ),
  updated_at = now()
WHERE c.is_active IS DISTINCT FROM false;
